### ISSUE TITLE
QSTEM/Master: Input .CFG overwritten by total projected potential

### ISSUE THREAD

**Issue by robbmcleod** [QSTEM/QSTEM#25]
Stemlib.cpp :: make3Dslices() has some variable confusion

Function has (input) FILE fileName as an argument and then declares (output) FILE filename. Needless to say this causes confusion and at the bottom of the function the total projected potential is written to the (input) file, overwriting the original .cfg file used to run stem3.exe.  

FIX: Rename variables to fileIn and fileOut respectively.  Correct sprintf of projected potential at bottom of function.  

Working code fragment:
# ifndef WIN32

```
        sprintf(fileOut,"%s/%s%d.img",muls->folder,muls->fileBase,iz);
```
# else

```
        sprintf(fileOut,"%s\\%s%d.img",muls->folder,muls->fileBase,iz);
```
# endif

```
        if (muls->printLevel >= 3)
            printf( "Saving (complex) potential layer %d to file %s (r: %g..%g)\n", iz, fileOut, ddx, ddy );

        imageIO->SetThickness(muls->sliceThickness);
        sprintf(buf,"Projected Potential (slice %d)",iz);        
        imageIO->SetComment(buf);
        imageIO->WriteComplexImage( (void **)muls->trans[iz], fileOut );
    } // loop through all slices
} /* end of if savePotential ... */
if (muls->saveTotalPotential) {
    if (tempPot == NULL) tempPot = float2D(muls->potNx,muls->potNy,"total projected potential");

    for (ix=0;ix<muls->potNx;ix++) for (iy=0;iy<muls->potNy;iy++) {
        tempPot[ix][iy] = 0;
        for (iz=0;iz<nlayer;iz++) tempPot[ix][iy] += muls->trans[iz][ix][iy][0];
    }

    for (ddx=tempPot[0][0],ddy = potVal,ix=0;ix<muls->potNy*muls->potNx;potVal = tempPot[0][++ix]) {
        if (ddy<potVal) ddy = potVal; 
        if (ddx>potVal) ddx = potVal; 
    }
```
# ifndef WIN32

```
    sprintf(fileOut,"%s/%sProj.img",muls->folder,muls->fileBase);   
```
# else

```
    // RAM DEBUG : this is overwriting the original config file, why?  is filename something else?
    // RAM RESOLVED: both fileName and filename were defined above...
    sprintf( fileOut, "%s\\%sProj.img", muls->folder, muls->fileBase );
```
# endif

```
    if (muls->printLevel >= 2)
        printf( "Saving total projected potential to file %s (r: %g..%g)\n", fileOut, ddx, ddy );
    imageIO->SetThickness(nlayer*muls->sliceThickness);
    sprintf(buf,"Projected Potential (sum of %d slices)",muls->slices);
    imageIO->SetComment(buf);
    imageIO->WriteRealImage( (void **)tempPot, fileOut );
}
```

**Comment by msarahan** [comment]
Thanks for sorting this out.  Can you please make a commit to your fork that includes this fix, then do a Pull Request?  That would be the easiest way for me to ensure that this fix gets applied correctly.

**Comment by robbmcleod** [comment]
I think it would be best if I wait a few weeks and bundle it with other
fixes so as not to have a drip-drip-drip of minor changes to manage.

On Mon, Apr 14, 2014 at 6:55 PM, Mike Sarahan notifications@github.comwrote:

> Thanks for sorting this out. Can you please make a commit to your fork
> that includes this fix, then do a Pull Request? That would be the easiest
> way for me to ensure that this fix gets applied correctly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QSTEM/QSTEM/issues/25#issuecomment-40390295
> .

## 

Robert McLeod, Ph.D.
Fondation Nanosciences (NSF) &
DSM/INAC/SP2M/LEMMA
Bat. 51 - P. B221B Minatec
17 rue des Martyrs, GRENOBLE Cedex 9
Tél: 04.38.78.04.44
Robert.MCLEOD@cea.fr
robbmcleod@gmail.com
www.researchgate.net/profile/Robert_Mcleod5/
